name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Vitor-dev2705
          outputs: snake.svg

      - name: Commit snake
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add snake.svg
          git commit -m "update snake"
          git push